// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqzj4He1eAn1URAhfMv0Tiznu-h_rOcCg',
    appId: '1:190288872359:web:e32a08ffb57f60e300ec82',
    messagingSenderId: '190288872359',
    projectId: 'barber-shop-cb926',
    authDomain: 'barber-shop-cb926.firebaseapp.com',
    storageBucket: 'barber-shop-cb926.firebasestorage.app',
    measurementId: 'G-WDMZS5V0S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl9WmwZoCz-rIkawZw-5iUA-gMEKENOdE',
    appId: '1:190288872359:android:196280b33330184300ec82',
    messagingSenderId: '190288872359',
    projectId: 'barber-shop-cb926',
    storageBucket: 'barber-shop-cb926.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCQqcWasUBdqCDqt04L_j7JLHSlI3xVCA',
    appId: '1:190288872359:ios:7c64857942f995c700ec82',
    messagingSenderId: '190288872359',
    projectId: 'barber-shop-cb926',
    storageBucket: 'barber-shop-cb926.firebasestorage.app',
    iosClientId: '190288872359-q4ib6onmsccm2l7psob0eim7tpdsvijs.apps.googleusercontent.com',
    iosBundleId: 'com.example.userbarber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCQqcWasUBdqCDqt04L_j7JLHSlI3xVCA',
    appId: '1:190288872359:ios:7c64857942f995c700ec82',
    messagingSenderId: '190288872359',
    projectId: 'barber-shop-cb926',
    storageBucket: 'barber-shop-cb926.firebasestorage.app',
    iosClientId: '190288872359-q4ib6onmsccm2l7psob0eim7tpdsvijs.apps.googleusercontent.com',
    iosBundleId: 'com.example.userbarber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqzj4He1eAn1URAhfMv0Tiznu-h_rOcCg',
    appId: '1:190288872359:web:c4309584e9792c0900ec82',
    messagingSenderId: '190288872359',
    projectId: 'barber-shop-cb926',
    authDomain: 'barber-shop-cb926.firebaseapp.com',
    storageBucket: 'barber-shop-cb926.firebasestorage.app',
    measurementId: 'G-JRTR1TQ5E1',
  );
}
